import sys
from pathlib import Path
from backend.assistant.retrieval import search_by_type
from backend.learner.learning import _load_analyzed_tasks_v3




def cmd_search(args):
    tags = [t.strip() for t in args.tags.split(',') if t.strip()] if hasattr(args, 'tags') and args.tags else None
    
    print(f"Search query: \"{args.query}\"")
    print(f"Limit: {args.limit}")
    if tags:
        print(f"Tags filter: {', '.join(tags)}")
    if args.output:
        print(f"Output: {args.output}")
    print()
    
    try:
        task_type, rules = search_by_type(args.query, limit=args.limit, tags=tags)
        
        print("=" * 80)
        print(f"DETECTED TYPE: {task_type}")
        print("=" * 80)
        print(f"\nFound {len(rules)} {task_type} rules\n")
        
        if rules:
            print(f"RELEVANT RULES ({len(rules)} result{'s' if len(rules) != 1 else ''})")
            print("=" * 80)
            for i, rule in enumerate(rules, 1):
                print(f"\n{i}. [Confidence: {rule.confidence}/10]")
                print(f"   {rule.rule}")
                print(f"   Reasoning: {rule.reasoning[:150]}{'...' if len(rule.reasoning) > 150 else ''}")
        else:
            print(f"No {task_type} rules found matching your query.")
        
        # If output file specified, write markdown
        if args.output:
            markdown_lines = []
            markdown_lines.append(f"# Relevant Rules for: {args.query}\n")
            markdown_lines.append(f"*Generated by zoro search on {Path().cwd()}*\n")
            markdown_lines.append(f"\n## Detected Task Type: {task_type}\n\n")
            
            if rules:
                markdown_lines.append("## 📚 Learning Rules\n")
                for rule in rules:
                    markdown_lines.append(f"### [{rule.confidence}/10 confidence] {rule.rule}\n")
                    markdown_lines.append(f"**Reasoning:** {rule.reasoning}\n")
            else:
                markdown_lines.append("*No relevant rules found for this query.*\n")
            
            # Write to file
            output_path = Path(args.output)
            output_path.parent.mkdir(parents=True, exist_ok=True)
            output_path.write_text('\n'.join(markdown_lines))
            print(f"\n✓ Wrote {len(rules)} rules to {args.output}")
        
        print(f"\nTotal: {len(rules)} rule{'s' if len(rules) != 1 else ''} found")
        print()
    
    except Exception as e:
        print(f"Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
