export const colors = {
  green: '#87ae73',      // Your original preferred green!
  darkGreen: '#6b8a5c',  // Your original dark green
  blue: '#5BB9C2',
  red: '#9a4e4e',
  gold: '#FDB813',
  grey: '#9e9e9e',
  white: '#ffffff',
  black: '#000000',
  text: '#213126',
  mutedText: '#667361',
  subtleText: '#555555',
  secondaryText: '#666666',
  strongText: '#333333',
  textOnDark: '#e0e0e0',
  textMutedOnDark: '#b0b0b0',
  divider: '#d6dfd2',
  dividerStrong: '#d0d0d0',
  dividerMuted: '#e2e2e2',
  surface: '#ffffff',
  surfaceSubtle: '#fafcf9',
  surfaceTint: '#f6fbf3',
  surfaceTintHover: '#eef6e9',
  surfaceMuted: '#f5f5f5',
  surfaceMutedAlt: '#f8f8f8',
  surfaceMutedSoft: '#f7f7f7',
  surfaceNeutral: '#f4f4f4',
  surfaceDark: '#1e1e1e',
  surfaceInfo: '#f0f7ff',
  surfaceInfoBorder: '#e3f2fd',
  surfaceWarning: '#fff4e5',
  surfaceWarningStrong: '#fff3e0',
  surfaceWarningAlt: '#fff8e8',
  surfaceWarningMuted: '#fffaf0',
  surfaceSuccess: '#e8f5e9',
  surfaceSuccessAlt: '#edf7ed',
  surfaceSuccessSoft: '#eef8ee',
  surfaceSuccessTint: '#eef9f0',
  surfaceSuccessStrong: '#dff3df',
  surfaceDanger: '#ffeceb',
  surfaceInfoAlt: '#ecf3ff',
  surfaceGreenSoft: '#ecf6e8',
  surfaceGreenTint: '#f4faf1',
  infoText: '#1d4f95',
  successText: '#1b5e20',
  warningText: '#8a5400',
  warningTextStrong: '#9b6b00',
  dangerText: '#a72525',
  warningAccent: '#e65100',
  warningBorder: '#ffb74d',
  confidenceMedium: '#ff9800',
  confidenceLow: '#f44336',
} as const;

export type ColorName = keyof typeof colors;
